import React, { useState } from 'react'

export default function Home() {
  const [running, setRunning] = useState(false)
  const [result, setResult] = useState<any>(null)
  const [auditId, setAuditId] = useState('')
  const [auditResult, setAuditResult] = useState<any>(null)

  async function runReminders() {
    setRunning(true)
    setResult(null)
    try {
      const r = await fetch('/api/sendReminders')
      const j = await r.json()
      setResult(j)
    } catch (err) {
      setResult({ error: String(err) })
    } finally {
      setRunning(false)
    }
  }

  async function runAudit() {
    if (!auditId) return
    setAuditResult(null)
    try {
      const r = await fetch(`/api/audit/${encodeURIComponent(auditId)}`)
      const j = await r.json()
      setAuditResult(j)
    } catch (err) {
      setAuditResult({ error: String(err) })
    }
  }

  return (
    <main className="container">
      <header className="header">
        <div className="brand">
          <div className="logo">BS</div>
          <div>
            <h1 className="title">Brite Spark</h1>
            <div className="subtitle">Reminder That Reaches — Prototype</div>
          </div>
        </div>
        <div className="small muted">Ready • <strong>Demo</strong></div>
      </header>

      <div className="grid">
        <div>
          <div className="card">
            <h2 style={{marginTop:0}}>Run Reminders</h2>
            <p className="muted">Trigger the reminder job using the server-side logic (mock channels).</p>
            <div style={{display:'flex',gap:12,alignItems:'center'}}>
              <button className="btn" onClick={runReminders} disabled={running}>{running ? 'Running…' : 'Run Reminders Now'}</button>
              <div className="muted small">Runs against seeded dataset and records audit events.</div>
            </div>
            {result && (
              <div style={{marginTop:16}}>
                <h3 style={{margin:0}}>Result</h3>
                <div className="pre" style={{marginTop:8}}>{JSON.stringify(result, null, 2)}</div>
              </div>
            )}
          </div>

          <div className="card">
            <h2 style={{marginTop:0}}>APIs</h2>
            <ul>
              <li><a href="/api/sendReminders">/api/sendReminders</a> — run reminder job (returns JSON)</li>
              <li><a href="/api/health">/api/health</a> — health check</li>
              <li><a href="/api/audit/RS-4121">/api/audit/[residentId]</a> — resident audit endpoint</li>
            </ul>
          </div>
        </div>

        <aside>
          <div className="card">
            <h3 style={{marginTop:0}}>Audit Resident</h3>
            <div style={{display:'flex',gap:8,marginTop:8}}>
              <input className="input" value={auditId} onChange={e => setAuditId(e.target.value)} placeholder="Resident ID (e.g. RS-4121)" />
              <button className="btn" onClick={runAudit}>Get Audit</button>
            </div>
            {auditResult && (
              <div style={{marginTop:12}}>
                <div className="pre">{JSON.stringify(auditResult, null, 2)}</div>
              </div>
            )}
          </div>

          <div className="card" style={{marginTop:12}}>
            <h4 style={{marginTop:0}}>Run Summary</h4>
            <div className="muted small">Download the latest run summary files generated by the reminder job.</div>
            <div style={{marginTop:10,display:'flex',gap:8}}>
              <a className="btn" href="/api/run-summary" style={{textDecoration:'none'}}>Download JSON</a>
              <a className="btn" href="/api/run-summary-csv" style={{textDecoration:'none'}}>Download CSV</a>
            </div>
          </div>
        </aside>
      </div>

      <div className="footer">Built for demo • Direction CR-2026/11 enforcement included</div>
    </main>
  )
}
